### ISSUE TITLE
Check for updates of duplicate steps

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#445] opened 2015-10-19 21:41 UTC
I clicked the Check for updates button on my Micall pipeline, and both copies of `censor_fastq` showed the updated icon. However, when I saved the pipeline, only one of them was updated. Could it be because I had two steps with the same name? There might be a related problem displaying run status when two steps have the same name.

I think there might also be problems when the driver script has updates as well as a dependency.

* [x] Don't create two methods or two code resource revisions when there's a new code resource revision or dependency.
* [x] Don't display two methods in the drop downs on the pipeline assembly page.
* [x] Check for problems when driver script has an update as well as a dependency.
* [x] Check for problems in run status when two steps have the same method.

**Comment by rhliang** [comment] 2016-02-17 19:14
Not sure if this is the cause of the issue, but I noticed that the `find_update_steps` method will create new Methods for all steps with updated CodeResourceRevisions regardless of whether the appropriate Method has already been created.  That is, suppose that step 1 and step 2 both do MethodX, based on CodeResourceX.  If you make a new revision of CodeResourceX, you'll get *two* new revisions of MethodX, both the same.

**Comment by rhliang** [comment] 2016-02-17 21:56
Just tested the same situation when you change a dependency of the CodeResourceRevision, and the same thing happens.  This time you also get two new CodeResourceRevisions, as well.

**Comment by ArtPoon** [comment] 2016-07-04 20:27
This has been fixed, pending confirmation before closing.

**Closed** 2016-07-11 22:57 UTC
Labels: bug, ready
