### ISSUE TITLE
Fleet crashes on startup

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/Kive#645] opened 2016-12-10 03:11 UTC
I was previously able to spin up a fleet of workers and run through the demo miseq pipeline on my laptop, but on the day of my presentation I was unable to start a fleet:
```
[Calculon.local:01944] [[14956,1],0] FORKING HNP: orted --hnp --set-sid --report-uri 5 --singleton-died-pipe 6 -mca state_novm_select 1 -mca ess_base_jobid 980156416
[Calculon.local:01944] [[14956,1],0] ORTE_ERROR_LOG: Unreachable in file dpm_orte.c at line 523
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[14956,2],3]) is on host: Calculon
  Process 2 ([[14956,1],0]) is on host: Calculon
  BTLs attempted: self sm vader

Your MPI job is now going to abort; sorry.
```

I tried restarting the laptop but it didn't help.  Figures that this would happen the day of my software demo 😆 

Kive version v0.8.5
Python 2.7.12
Django 1.9.12
mpi4py 1.3.1

**Comment by donkirkby** [comment] 2016-12-14 00:13
Sorry to hear that Kive had stage fright, Art. Have you had any success in finding the problem? Try running a simple script that scatters a range of numbers across the pool just to see if MPI is working at all.

On Octomore, we had to launch the fleet with `mpirun` to get it to work. It wouldn't work if we just launched `manage.py` directly.

This [blog post] has some suggestions for how to track down what communication protocols failed.

[blog post]: http://hpchcl.blogspot.ca/2013/03/open-mpi-error-message-mpi-process.html

**Comment by ArtPoon** [comment] 2016-12-14 02:07
Tried launching with `mpirun` but I got the same error spam.  I also confirmed that my installation of MPI is functional via `mpi4py` with the following script:
```
from mpi4py import MPI
my_rank = MPI.COMM_WORLD.Get_rank()
nprocs = MPI.COMM_WORLD.Get_size()
print 'node %d of %d reporting' % (my_rank, nprocs)
```

which yielded the expected output:
```
> mpirun -np 4 python test-mpi.py 
node 0 of 4 reporting
node 1 of 4 reporting
node 2 of 4 reporting
node 3 of 4 reporting
```

**Comment by ArtPoon** [comment] 2016-12-14 02:11
Now this is really weird.  I'm able to spin up workers now:
```
> ./manage.py runfleet -w 4
[Calculon.local:09479] [[6387,1],0] FORKING HNP: orted --hnp --set-sid --report-uri 5 --singleton-died-pipe 6 -mca state_novm_select 1 -mca ess_base_jobid 418578432
2016-12-13 18:08:54[INFO]fleet.Manager._startup(): Manager started on host Calculon.local
2016-12-13 18:08:54[INFO]fleet.Manager.take_rollcall(): Worker 1 on host Calculon.local has reported for duty
```
Just half an hour ago it wasn't working..

**Comment by rhliang** [comment] 2016-12-14 17:54
Huh.  You know what, I think I had this problem the last time *I* had to do a software demo of Kive (at CAHR, a couple of years ago).  It just magically disappeared then too.

**Comment by rhliang** [comment] 2016-12-20 21:32
@ArtPoon any (bad) luck reproducing this issue?  If it's come up twice in 3 years (and both times on Mac laptops) it's not necessarily clear how one would address this.

**Comment by ArtPoon** [comment] 2016-12-21 13:49
Wasn't able to reproduce last night. As you say, the conditions appear to be that the user is running Kive on a Mac laptop and about to do a software demo :-P

**Comment by donkirkby** [comment] 2016-12-21 18:21
I'm going to close this, since none of us can think of any way to track down the problem. We'll reopen if we see it more often.

**Closed by donkirkby** 2016-12-21 18:21 UTC
Labels: bug
