### ISSUE TITLE
Mounting RAW_DATA on the compute nodes using /etc/beowulf/fstab isn't working

### ISSUE THREAD

**Issue by rhliang** [cfe-lab/Kive#556] opened 2016-05-12 23:15 UTC
Noticed this when node 3 experienced some kind of crash on May 11 at right around 1:34PM.  It attempted to reboot but failed while trying to mount `/media/RAW_DATA`.  I tried it again, and again after modifying the `fstab` entry, to no avail, both times producing the following in `/var/log/beowulf/node.3`:

```
mount error 13 = Permission denied
```

Note that this also occurred when I tried to mount the same directory on node 2, but on a second attempt it worked.  This is possibly some kind of network issue.

It seems like my `fstab` entry was no good, and we just never found out until now because we didn't have any downtime since I first mounted them.  I'd like to fix the `fstab`, but I'll need to figure out how we can actually access that on the compute nodes.  Simply typing `bpsh [node number] mount /media/RAW_DATA` doesn't work because `/etc/beowulf/fstab` isn't accessible from the compute node.

**Comment by ArtPoon** [comment] 2016-05-24 17:19
The node crash and subsequent reboot attempt were most likely caused by a compute node exceeding its RAM; as far as I know there is no swap space for compute nodes (attempting to do this over the cluster network would be a bad idea).

**Comment by ArtPoon** [comment] 2016-05-24 17:21
Investigate why `fstab` isn't working the way we expect.  A possible fix would be to use an initialization script that is automatically run by the boot daemon to remount the `RAW_DATA` drive.

**Comment by donkirkby** [comment] 2016-06-17 21:54
I found that `/media/RAW_DATA` wasn't mounted on node 9, so I tried to mount it:

    sudo bpsh 9 mount -t cifs -o username=<USER>,password=<PASSWORD> //192.168.xxx.yyy/RAW_DATA /media/RAW_DATA

That failed with a message like 'cifs filesystem not supported'. Some searching led me to check for the cifs driver on all the nodes.

    bpsh -sap ls -l /lib/modules/2.6.18-348.18.1.el5.596g0000/kernel/fs/cifs

All the other nodes have a `cifs.ko` file in that directory, but node 9 has an empty directory.

Art is going to contact Penguin computing support.

**Comment by ArtPoon** [comment] 2016-06-17 22:12
Response from Penguin:

cifs.ko is the kernel module for Samba/ SMB. 

All the nodes should be using the kernel from the head node...however, it's possible that for some reason n9 had not been rebooted in a long time -- maybe after samba was set up on the head? 

Can you please reboot n9 and see if it persists?

**Comment by rhliang** [comment] 2016-06-20 16:50
If this hasn't already been resolved, maybe try `modprobe cifs` on node 9.  I don't know why node 9 didn't have the module already loaded.  I do remember running `modprobe` on all of the compute nodes, but the relevant line is in `/etc/beowulf/config`.

For reference, I followed Thuy's instructions: http://192.168.68.61/wiki/doku.php?id=mount_samba_cifs_shares_on_remote_nodes

**Comment by donkirkby** [comment] 2016-06-20 18:58
Using `modprobe` solved the problem. I followed Thuy's instructions, and it worked fine.

I'm leaving this issue open, because I think the nodes still don't mount the raw data share when they boot up.

**Comment by donkirkby** [comment] 2019-01-17 01:04
I don't think this is a problem anymore. Closing the issue.

**Closed by donkirkby** 2019-01-17 01:04 UTC
