### ISSUE TITLE
Permissions wrong on dataset folder

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/Kive#484] opened 2015-12-14 17:42 UTC
I got an error when I tried to upload a dataset through the API. When I looked, I found the permissions on the current dataset folder were wrong:

```
drwxrwsr-x 2 apache    kive  4096 Sep 30 19:36 2015_09
drwxrwsr-x 2 apache    kive 28672 Oct 30 15:18 2015_10
drwxrwsr-x 2 apache    kive 20480 Nov 26 14:55 2015_11
drwxr-sr-x 2 kivefleet kive  4096 Dec  8 16:49 2015_12
```

It looks like the kivefleet user created the folder with different permissions from the apache user. Either that, or the code changed some time in November.
I have manually changed the permissions, but we should try to fix the problem before January.

**Comment by ArtPoon** [comment] 2016-01-18 21:28
Duplicate of #490.

**Closed by ArtPoon** 2016-01-18 21:28 UTC
Labels: bug
